language: node_js
branches:
  only:
  - master
before_script: bash ./deploy/prepare.sh
script:
- ls -al deploy/v1/wapuu.json
- cat deploy/v1/wapuu.json | jq .
after_success: bash ./deploy/deploy.sh
env:
  global:
  - GH_REF: github.com/jawordpressorg/wapuu-api.git
  - secure: gPic2DobRlkaFsVbu86WIq/eVATo8wPEreOID8870Ba0QQeosfvpHa3gWV8vEtkk66WEwH2KfHZqyrvjpQlCq/lpF0gkIpwCpjytt2nHDNWxGgd1hqz/3K5CB+Ef7f2/90mNbJMoywVYwbmGvU65qa+tt0kdLyy/wlXjre53ccWh17ZDmTPPdTgIEigTr3b/i9/72C1fBgf1SdK6Pj8AE++9ypk4QTq641FGYUaZZbwaJ8AzG/UTpqPGCZIRskanyVcSTpwenzR5GlvmvaDUFMCOx6Tn4GtDch88p566/WVI6P1BHbaURDTnWUX4L0oY7Xb2gi2ghu6PvGYbrXi7aLalze3HwHLIhhEbTvSv/5o83j51PUr+eU86WXS1bBk50BVCYY4NlA6IcxomqoVTGecMdj9z2bsd3XEItb0GH/4ttuz/zqElaiIYJsBHGTbQ7VYpRt1l/FedJtsCiGLoTbt8OwO60xMhkQqIykL8uj7CCm+s7ZyqoG7+tY+EzbGdODHmHbQQ45dM/laHKWGnSkak2Bi4G3sZqlvyoVC4taGvc0AbTYNfnseKx3mFyXaDoDsEiqGo9ffs+a5TcRUV+G6iE12pTgl98Je3EDBgkAciqv1WKp/5Glb6R/ezflNqecOzCBlISl2v9u/Hr+DwCXApH9t33lTmbv1LkWldwaU=
